apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: windparkmanager
    user: wpm
    secureJsonData:
      password: '${POSTGRES_PASSWORD}'
    jsonData:
      sslmode: disable
      timescaledb: true
    access: proxy
